package com.yuanwei.android.constants;

public class ClinicalTrialDrugs {
	public static final String[] drugs = {
			"Abacavir",
			"Abarelix",
			"Abatacept",
			"Abciximab",
			"Acamprosate",
			"Acarbose",
			"Acebutolol",
			"Aceclofenac",
			"Acenocoumarol",
			"Acetaminophen",
			"Acetaminophen, hydrocodone drug combination",
			"Acetazolamide",
			"Acetic Acid",
			"Acetohexamide",
			"Acetorphan",
			"Acetovanillone",
			"Acetylcarnitine",
			"Acetylcholine",
			"Acetylcysteine",
			"Acetylmuramyl-Alanyl-Isoglutamine",
			"Acetylsalicylic acid lysinate",
			"Acidophilus",
			"Acifluorfen",
			"Acipimox",
			"Acitretin",
			"Aclacinomycins",
			"Acriflavine",
			"Actovegin",
			"Acyclovir",
			"Adalimumab",
			"Adapalene",
			"Adderall",
			"Adefovir",
			"Adefovir dipivoxil",
			"Adenosine",
			"Adenosine A1 Receptor Agonists",
			"Adenosine A1 Receptor Antagonists",
			"Adenosine Deaminase Inhibitors",
			"Adjuvants, Anesthesia",
			"Adjuvants, Immunologic",
			"Adrenergic Agents",
			"Adrenergic Agonists",
			"Adrenergic alpha-1 Receptor Antagonists",
			"Adrenergic alpha-Agonists",
			"Adrenergic alpha-Antagonists",
			"Adrenergic Antagonists",
			"Adrenergic beta-1 Receptor Antagonists",
			"Adrenergic beta-2 Receptor Agonists",
			"Adrenergic beta-3 Receptor Agonists",
			"Adrenergic beta-Agonists",
			"Adrenergic beta-Antagonists",
			"Adrenocorticotropic Hormone",
			"Adrenocorticotropin zinc",
			"Adrenomedullin",
			"Agglutinins",
			"Ajmaline",
			"Alanine",
			"Alanosine",
			"Alatrofloxacin",
			"Albendazole",
			"Albuterol",
			"Alclometasone dipropionate",
			"Aldesleukin",
			"Aldosterone Antagonists",
			"Alefacept",
			"Alemtuzumab",
			"Alendronate",
			"Alfalfa",
			"Alfentanil",
			"Alfuzosin",
			"Algestone",
			"Alginate, aluminium hydroxide, magnesium trisilicate, sodium bicarbonate drug...",
			"Alginic acid",
			"Alitretinoin",
			"Alizapride",
			"Alkylating Agents",
			"Allantoin",
			"Allicin",
			"Alliin",
			"Allopurinol",
			"Allyl sulfide",
			"Almotriptan",
			"Aloe",
			"Alogliptin",
			"Alosetron",
			"Alovudine",
			"Alpha 1-Antitrypsin",
			"Alpha-lipoic Acid",
			"Alpha-Methyltyrosine",
			"Alpha-MSH",
			"Alpha-Tocopherol",
			"Alprazolam",
			"Alprostadil",
			"Altretamine",
			"Aluminum chloride",
			"Aluminum Hydroxide",
			"Aluminum hydroxide, magnesium hydroxide, drug combination",
			"Aluminum hydroxide, magnesium hydroxide, simethicone drug combination",
			"Aluminum phosphate",
			"Aluminum sulfate",
			"Alverine",
			"Amantadine",
			"Ambroxol",
			"Amdinocillin",
			"Amdinocillin Pivoxil",
			"Amebicides",
			"American Elder",
			"Amifostine",
			"Amikacin",
			"Amiloride",
			"Amiloride, hydrochlorothiazide drug combination",
			"Aminaphthone",
			"Aminoglutethimide",
			"Aminolevulinic Acid",
			"Aminophylline",
			"Aminopterin",
			"Aminosalicylic Acid",
			"Amiodarone",
			"Amitriptyline",
			"Amitriptyline, perphenazine drug combination",
			"Amlexanox",
			"Amlodipine",
			"Amlodipine, atorvastatin drug combination",
			"Amlodipine, valsartan drug combination",
			"Ammonium trichloro(dioxoethylene-O,O'-)tellurate",
			"Amodiaquine",
			"Amodiaquine, artesunate drug combination",
			"Amonafide",
			"Amorolfine",
			"Amoxicillin",
			"Amoxicillin-Potassium Clavulanate Combination",
			"Amphetamine",
			"Amphotericin B",
			"Amphotericin B, deoxycholate drug combination",
			"Ampicillin",
			"Ampligen",
			"Amprenavir",
			"Amrubicin",
			"Amsacrine",
			"Anabolic Agents",
			"Anagrelide",
			"Analgesics",
			"Analgesics, Non-Narcotic",
			"Analgesics, Opioid",
			"Anastrozole",
			"Ancrod",
			"Androgen Antagonists",
			"Androgen Receptor Antagonists",
			"Androgens",
			"Andrographolide",
			"Anesthetics",
			"Anesthetics, Dissociative",
			"Anesthetics, General",
			"Anesthetics, Inhalation",
			"Anesthetics, Intravenous",
			"Anesthetics, Local",
			"Angelica",
			"Angiogenesis Inducing Agents",
			"Angiogenesis Inhibitors",
			"Angiogenesis Modulating Agents",
			"Angiogenin",
			"Angiopeptin",
			"Angiostatins",
			"Angiotensin I (1-7)",
			"Angiotensin II",
			"Angiotensin II Type 1 Receptor Blockers",
			"Angiotensin Receptor Antagonists",
			"Angiotensin-Converting Enzyme Inhibitors",
			"Angiotensinogen",
			"Anidulafungin",
			"Anise",
			"Anisodamine",
			"Annamycin",
			"Annexin A5",
			"Antacids",
			"Antazoline",
			"Anthelmintics",
			"Anthocyanidin",
			"Anthralin",
			"Anthranilic acid",
			"Anti-Allergic Agents",
			"Anti-Anxiety Agents",
			"Anti-Arrhythmia Agents",
			"Anti-Asthmatic Agents",
			"Anti-Bacterial Agents",
			"Anti-Dyskinesia Agents",
			"Anti-HIV Agents",
			"Anti-Infective Agents   9",
			"Anti-Infective Agents, Local",
			"Anti-Infective Agents, Urinary",
			"Anti-Inflammatory Agents",
			"Anti-Inflammatory Agents, Non-Steroidal",
			"Anti-Obesity Agents",
			"Anti-Retroviral Agents",
			"Anti-Ulcer Agents",
			"Antibiotics, Antineoplastic",
			"Antibiotics, Antitubercular",
			"Antibodies",
			"Antibodies, Anti-Idiotypic",
			"Antibodies, Anticardiolipin",
			"Antibodies, Antineutrophil Cytoplasmic",
			"Antibodies, Antiphospholipid",
			"Antibodies, Bispecific",
			"Antibodies, Monoclonal",
			"Antibodies, Neoplasm",
			"Anticarcinogenic Agents",
			"Anticholesteremic Agents",
			"Anticoagulants",
			"Anticonvulsants",
			"Antidepressive Agents",
			"Antidepressive Agents, Second-Generation",
			"Antidepressive Agents, Tricyclic",
			"Antidiarrheals",
			"Antidotes",
			"Antiemetics",
			"Antifibrinolytic Agents",
			"Antifungal Agents",
			"Antigen-Antibody Complex",
			"Antihypertensive Agents",
			"Antilymphocyte Serum",
			"Antimalarials",
			"Antimanic Agents",
			"Antimetabolites",
			"Antimetabolites, Antineoplastic",
			"Antimitotic Agents",
			"Antimony Sodium Gluconate",
			"Antimutagenic Agents",
			"Antineoplastic Agents, Alkylating",
			"Antineoplastic Agents, Hormonal",
			"Antineoplastic Agents, Phytogenic",
			"Antioxidants",
			"Antiparasitic Agents",
			"Antiparkinson Agents",
			"Antiprotozoal Agents",
			"Antipruritics",
			"Antipsychotic Agents",
			"Antipyretics",
			"Antipyrine",
			"Antirheumatic Agents",
			"Antisickling Agents",
			"Antithrombin III",
			"Antithrombin Proteins",
			"Antithrombins",
			"Antithyroid Agents",
			"Antitoxins",
			"Antitubercular Agents",
			"Antitussive Agents",
			"Antivenins",
			"Antiviral Agents",
			"Antivitamins K",
			"Apaziquone",
			"Apomorphine",
			"Appetite Depressants",
			"Appetite Stimulants",
			"Apraclonidine",
			"Aprepitant",
			"Apricot",
			"Aprotinin",
			"Arachidonic Acid",
			"Argatroban",
			"Arginine",
			"Arginine butyrate",
			"Arginine Vasopressin",
			"Arginyl-glycyl-aspartic acid",
			"Aripiprazole",
			"Aristolochic acid I",
			"Arnica",
			"Aromatase Inhibitors",
			"Arotinolol",
			"Arsenic trioxide",
			"Artemether",
			"Artemether-lumefantrine combination",
			"Artemisinine",
			"Artemisinins",
			"Artesunate",
			"Arthrotec",
			"Artichoke",
			"Ascorbate-2-phosphate",
			"Ascorbic Acid",
			"Asenapine",
			"Ashwagandha",
			"Asparaginase",
			"Aspartic Acid",
			"Aspirin",
			"Aspirin, aluminum hydroxide, magnesium hydroxide drug combination",
			"Aspirin, dipyridamole drug combination",
			"Astragalus",
			"Astressin",
			"Atamestane",
			"Atazanavir",
			"Atenolol",
			"Atipamezole",
			"Atomoxetine",
			"Atorvastatin",
			"Atosiban",
			"Atovaquone",
			"Atracurium",
			"Atreleuton",
			"Atrial natriuretic factor prohormone (9-9)",
			"Atropine",
			"Atropine sulfate-diphenoxylate hydrochloride combination",
			"Auranofin",
			"Autoantibodies",
			"Autonomic Agents",
			"Autumn Crocus",
			"Azacitidine",
			"Azaperone",
			"Azathioprine",
			"Azelaic acid",
			"Azelastine",
			"Azimilide",
			"Azithromycin",
			"Azosemid",
			"Aztreonam",
			"Bacampicillin",
			"Bacitracin",
			"Bacitracin zinc, neomycin sulfate, polymyxin B, drug combination",
			"Baclofen",
			"Bacterial lysate",
			"Bactericidal permeability increasing protein",
			"Balsalazide",
			"Bambuterol",
			"Barley",
			"Basiliximab",
			"BB 9",
			"BBR 9",
			"BCG Vaccine",
			"Beclomethasone",
			"Bee Products",
			"Belladonna",
			"Belotecan",
			"Benazepril",
			"Bendamustine",
			"Bendroflumethiazide",
			"Benfluorex",
			"Benidipine",
			"Benphothiamine",
			"Benserazide",
			"Bentonite",
			"Benzalkonium Compounds",
			"Benzbromarone",
			"Benzethonium",
			"Benzimidazole",
			"Benzoates",
			"Benzocaine",
			"Benzonatate",
			"Benzonidazole",
			"Benzophenone",
			"Benzoyl Peroxide",
			"Benztropine",
			"Benzydamine",
			"Benzyl Alcohol",
			"Beractant",
			"Beraprost",
			"Beta 2-Glycoprotein I",
			"Beta Carotene",
			"Beta-1,3-glucan",
			"Beta-Endorphin",
			"Beta-hydroxy-beta-methylbutyrate",
			"Beta-Lactams",
			"Beta-lapachone",
			"Betahistine",
			"Betaine",
			"Betamethasone",
			"Betamethasone 9-Valerate",
			"Betamethasone acetate phosphate",
			"Betamethasone dipropionate, betamethasone sodium phosphate drug combination",
			"Betamethasone sodium phosphate",
			"Betamethasone-9,9-dipropionate",
			"Betaxolol",
			"Bethanechol",
			"Betulinic acid",
			"Bevacizumab",
			"Bexarotene",
			"Bezafibrate",
			"BI 9",
			"Biapenem",
			"Bicalutamide",
			"Bifidobacterium",
			"Bifonazole",
			"Bilberry",
			"Bile Acids and Salts",
			"Bilirubin",
			"Bimatoprost",
			"Biochanin A",
			"Biotin",
			"Biperiden",
			"Bis-neodecanoato-1,2-diaminocyclohexaneplatinum(II)",
			"Bisacodyl",
			"Bismuth",
			"Bismuth subsalicylate",
			"Bismuth tripotassium dicitrate",
			"Bisoprolol",
			"Bisphenol A",
			"Bitter Melon",
			"Bitter Orange",
			"Bivalirudin",
			"Bizelesin",
			"Black Cohosh",
			"Black Currant",
			"Blackberry",
			"Bleomycin",
			"Blood Coagulation Factor Inhibitors",
			"Blood Substitutes",
			"Blueberry",
			"Bombesin",
			"Bone Density Conservation Agents",
			"Borage",
			"Borage oil",
			"Boron",
			"Bortezomib",
			"Bosentan",
			"Boswellic acid",
			"Botulinum Antitoxin",
			"Botulinum Toxins",
			"Botulinum Toxins, Type A",
			"BQ 9",
			"Bradykinin",
			"Bredinin",
			"Brewer's Yeast",
			"Brimonidine",
			"Brinzolamide",
			"Brivudine",
			"Bromazepam",
			"Bromfenac",
			"Bromhexine",
			"Bromides",
			"Bromocriptine",
			"Bromodeoxyuridine",
			"Brompheniramine",
			"Bronchodilator Agents",
			"Bronopol",
			"Brotizolam",
			"Bryostatin 1",
			"Buchu",
			"Bucillamine",
			"Bucindolol",
			"Budesonide",
			"Bufanolides",
			"Bumetanide",
			"Bunazosin",
			"Bupivacaine",
			"Buprenorphine",
			"Bupropion",
			"Burdock",
			"Buserelin",
			"Buspirone",
			"Busulfan",
			"Butenafine",
			"Buthionine Sulfoximine",
			"Butoconazole",
			"Butorphanol",
			"Butylated Hydroxytoluene",
			"Butylscopolammonium Bromide",
			"Butyric Acid",
			"Cabergoline",
			"Cadexomer iodine",
			"Caffeine",
			"Caffeine citrate",
			"Caffeine, sodium benzoate drug combination",
			"Calamus",
			"Calanolide A",
			"Calcifediol",
			"Calciferol",
			"Calcimimetic Agents",
			"Calcipotriene",
			"Calcitonin",
			"Calcitonin Gene-Related Peptide",
			"Calcitriol",
			"Calcium acetate",
			"Calcium Carbonate",
			"Calcium Channel Blockers",
			"Calcium Dobesilate",
			"Calcium heparin",
			"Calcium polycarbophil",
			"Calcium Supplement",
			"Calcium, Dietary",
			"Calendula",
			"Calfactant",
			"Campath 1G",
			"Camphor",
			"Camptothecin",
			"Candesartan",
			"Candesartan cilexetil",
			"Cangrelor",
			"Canrenoate Potassium",
			"Canrenone",
			"Cantharidin",
			"Canthaxanthin",
			"Capecitabine",
			"Capreomycin",
			"Caproate",
			"Capsaicin",
			"Captopril",
			"Caraway",
			"Carbachol",
			"Carbamazepine",
			"Carbenicillin",
			"Carbenicillin indanyl",
			"Carbetocin",
			"Carbidopa",
			"Carbidopa, levodopa drug combination",
			"Carbimazole",
			"Carbocysteine",
			"Carbogen",
			"Carbon fiber",
			"Carbon Monoxide",
			"Carbonic Anhydrase Inhibitors",
			"Carboplatin",
			"Carbopol 9",
			"Carboprost",
			"Carboprost tromethamine",
			"Carboxyamido-triazole",
			"Carboxymethylcellulose Sodium",
			"Cardiac Glycosides",
			"Cardioplegic Solutions",
			"Cardiotonic Agents",
			"Cardiovascular Agents",
			"Carfentanil",
			"Cariostatic Agents",
			"Carisoprodol",
			"Carmustine",
			"Carnitine",
			"Carotenoids",
			"Carteolol",
			"Carticaine",
			"Carvedilol",
			"Caseins",
			"Caspofungin",
			"Cassava",
			"Castor",
			"Castor Oil",
			"Cat's Claw",
			"Catechin",
			"Catechol",
			"Cathartics",
			"Cayenne",
			"CD4 Immunoadhesins",
			"Cefaclor",
			"Cefadroxil",
			"Cefazolin",
			"Cefdinir",
			"Cefditoren",
			"Cefditoren pivoxil",
			"Cefepime",
			"Cefixime",
			"Cefmetazole",
			"Cefonicid",
			"Cefoperazone",
			"Cefotaxime",
			"Cefotetan",
			"Cefoxitin",
			"Cefpirome",
			"Cefpodoxime",
			"Cefpodoxime proxetil",
			"Cefprozil",
			"Ceftazidime",
			"Ceftibuten",
			"Ceftizoxime",
			"Ceftriaxone",
			"Cefuroxime",
			"Cefuroxime axetil",
			"Celecoxib",
			"Celiprolol",
			"Cellulose, Oxidized",
			"Central Nervous System Depressants",
			"Central Nervous System Stimulants",
			"Cephalexin",
			"Cephalosporins",
			"Cephradine",
			"Cerebrolysin",
			"Cerium nitrate",
			"Certoparin",
			"Cethromycin",
			"Cetirizine",
			"Cetrorelix",
			"Cetuximab",
			"Cetylpyridinium",
			"Cevimeline",
			"Chamomile",
			"Charcoal",
			"Chaste Tree",
			"Chelating Agents",
			"Chenodeoxycholic Acid",
			"Chicory",
			"Chinese Rhubarb",
			"Chinese Salvia",
			"Chinese Skullcap",
			"Chinese Yam",
			"Chitin",
			"Chitosan",
			"Chloral Hydrate",
			"Chlorambucil",
			"Chloramine-T",
			"Chloramphenicol",
			"Chloramphenicol succinate",
			"Chlordesmethyldiazepam",
			"Chlordiazepoxide",
			"Chlorhexidine",
			"Chlorhexidine gluconate",
			"Chlorhexidine, thymol drug combination",
			"Chlorine dioxide",
			"Chlormadinone Acetate",
			"Chlorogenic",
			"Chlorophyllin",
			"Chloroprocaine",
			"Chloroquine",
			"Chloroquine diphosphate",
			"Chlorothiazide",
			"Chlorpheniramine",
			"Chlorpheniramine, phenylpropanolamine drug combination",
			"Chlorproguanil",
			"Chlorpromazine",
			"Chlorpropamide",
			"Chlorquinaldol",
			"Chlortetracycline",
			"Chlorthalidone",
			"Chlorzoxazone",
			"Cholagogues and Choleretics",
			"Cholecalciferol",
			"Cholecystokinin",
			"Cholera Toxin",
			"Cholestyramine Resin",
			"Cholic Acids",
			"Choline",
			"Choline magnesium trisalicylate",
			"Cholinergic Agents",
			"Cholinergic Agonists",
			"Cholinergic Antagonists",
			"Cholinesterase Inhibitors",
			"Chondroitin",
			"Chorionic Gonadotropin",
			"Chromium",
			"CI 9",
			"Ciclesonide",
			"Ciclopirox",
			"Cidofovir",
			"Cifenline",
			"Cilastatin",
			"Cilazapril",
			"Cilnidipine",
			"Cilomilast",
			"Cilostazol",
			"Cimetidine",
			"Cineole",
			"Cinnamic aldehyde",
			"Cinnamon",
			"Cinnarizine",
			"Cinoxacin",
			"Ciprofibrate",
			"Ciprofloxacin",
			"Ciprofloxacin, hydrocortisone drug combination",
			"Cisapride",
			"Cisatracurium",
			"Cisplatin",
			"Citalopram",
			"Citrate",
			"Citric Acid",
			"Cladribine",
			"Clarithromycin",
			"Clavulanic Acids",
			"Clemastine",
			"Clenbuterol",
			"Clidinium",
			"Clindamycin",
			"Clindamycin-2-phosphate",
			"Clobazam",
			"Clobetasol",
			"Clobetasone butyrate",
			"Clocortolone pivalate",
			"Clodronic Acid",
			"Clofarabine",
			"Clofazimine",
			"Clofibrate",
			"Clofibric Acid",
			"Clomiphene",
			"Clomipramine",
			"Clonazepam",
			"Clonidine",
			"Clonixin",
			"Clopenthixol",
			"Clopidogrel",
			"Cloprostenol",
			"Clorazepate Dipotassium",
			"Clothiapine",
			"Clotrimazole",
			"Cloxacillin",
			"Clozapine",
			"CNI 9",
			"Coagulants",
			"Coagulase",
			"Cobalamin",
			"Cobalt",
			"Cocaethylene",
			"Cocaine",
			"Coconut",
			"Cod Liver Oil",
			"Codeine",
			"Coenzyme Q9",
			"Cola",
			"Colchicine",
			"Cold agglutinins",
			"Colesevelam",
			"Colestipol",
			"Colforsin",
			"Colistin",
			"Colocynth",
			"Combretastatin",
			"Combretastatin A-4",
			"Common Bean",
			"Complement C1",
			"Complement C1 Inactivator Proteins",
			"Complement C1 Inhibitor Protein",
			"Complement C1s",
			"Complement Factor H",
			"Complement Factor I",
			"Complement System Proteins",
			"Contact Lens Solutions",
			"Contraceptive Agents",
			"Contraceptive Agents, Female",
			"Contraceptive Agents, Male",
			"Contraceptives, Oral",
			"Contraceptives, Oral, Combined",
			"Contraceptives, Oral, Hormonal",
			"Contraceptives, Oral, Sequential",
			"Contraceptives, Postcoital",
			"Convulsants",
			"Copolymer 1",
			"Copper",
			"Copper Sulfate",
			"Cordycepin",
			"Coriander",
			"Corticosterone",
			"Corticotropin-Releasing Hormone",
			"Cortisol succinate",
			"Cortisone",
			"Cortisone acetate",
			"Cortivazol",
			"Cosyntropin",
			"Coumarins",
			"CPG-oligonucleotide",
			"Cranberry",
			"Creatine",
			"Cromolyn Sodium",
			"Cryoprotective Agents",
			"Cryptoxanthin",
			"Curare",
			"Curcumin",
			"Curdlan sulfate",
			"Cyanocobalamin",
			"Cycletanide",
			"Cyclin-Dependent Kinase Inhibitor Proteins",
			"Cyclo(Trp-Asp-Pro-Val-Leu)",
			"Cyclobenzaprine",
			"Cyclooxygenase 2 Inhibitors",
			"Cyclooxygenase Inhibitors",
			"Cyclopentolate",
			"Cyclophosphamide",
			"CycloProvera",
			"Cycloserine",
			"Cyclosporins",
			"Cyproheptadine",
			"Cyproterone",
			"Cyproterone Acetate",
			"Cystatins",
			"Cysteamine",
			"Cysteine",
			"Cysteinyl-leukotriene",
			"Cytarabine",
			"Cytidine Diphosphate Choline",
			"Cytotoxic T-lymphocyte antigen 4",
			"D 99",
			"DA 9",
			"Dacarbazine",
			"Daclizumab",
			"Dactinomycin",
			"Daidzein",
			"Dalbavancin",
			"Dalcetrapib",
			"Dalfopristin",
			"Dalteparin",
			"Dan-shen root extract",
			"Danaproid",
			"Danazol",
			"Dandelion",
			"Dantrolene",
			"Dapsone",
			"Daptomycin",
			"Darbepoetin alfa",
			"Darifenacin",
			"Darunavir",
			"Dasatinib",
			"Date Palm",
			"Daunorubicin",
			"Deamino Arginine Vasopressin",
			"Debrisoquin",
			"Decanoic acid",
			"Decitabine",
			"Defensins",
			"Deferasirox",
			"Deferiprone",
			"Deferoxamine",
			"Defibrotide",
			"Deflazacort",
			"Dehydroepiandrosterone",
			"Delapril",
			"Delavirdine",
			"Demeclocycline",
			"Denileukin diftitox",
			"Deoxycholic Acid",
			"Deoxyglucose",
			"Deoxyuridine",
			"Dequalinium",
			"Dermatologic Agents",
			"Desflurane",
			"Desipramine",
			"Desirudin",
			"Desloratadine",
			"Deslorelin",
			"Desogestrel",
			"Desonide",
			"Desoximetasone",
			"Detox adjuvant",
			"Deuterium Oxide",
			"Devil's Claw",
			"Dexamethasone",
			"Dexamethasone 9-phosphate",
			"Dexamethasone acetate",
			"Dexamethasone, neomycin, polymyxin B drug combination",
			"Dexchlorpheniramine",
			"Dexetimide",
			"Dexfenfluramine",
			"Dexketoprofen trometamol",
			"Dexmedetomidine",
			"Dextrans",
			"Dextroamphetamine",
			"Dextromethorphan",
			"Dextropropoxyphene",
			"DHEA (Dehydroepiandrosterone)",
			"Diacetylrhein",
			"Diallyl Sulfide",
			"Diane",
			"Diazepam",
			"Diazoxide",
			"Dibekacin",
			"Dichlororibofuranosylbenzimidazole",
			"Dichlorphenamide",
			"Diclazuril",
			"Diclofenac",
			"Diclofenac hydroxyethylpyrrolidine",
			"Dicloxacillin",
			"Didanosine",
			"Dideoxynucleosides",
			"Dienogest",
			"Diethylcarbamazine",
			"Diethylenetriamine",
			"Diethylpropion",
			"Diethylstilbestrol",
			"Diflunisal",
			"Difluprednate",
			"Digitalis",
			"Digitoxin",
			"Digoxin",
			"Digoxin-like factors",
			"Dihematoporphyrin Ether",
			"Dihydralazine",
			"Dihydrexidine",
			"Dihydrocodeine",
			"Dihydroergotamine",
			"Dihydroergotoxine",
			"Dihydroquinghaosu",
			"Dihydrotachysterol",
			"Dihydrotestosterone",
			"Dihydrouracil Dehydrogenase (NADP)",
			"Dihydroxycholecalciferols",
			"Dihydroxyphenylalanine",
			"Dill",
			"Diltiazem",
			"Dimenhydrinate",
			"Dimethindene",
			"Dimethyl fumarate",
			"Dimethyl sulfone",
			"Dimethyl Sulfoxide",
			"Diminazene aceturate",
			"Dinoprost",
			"Dinoprost tromethamine",
			"Dinoprostone",
			"Dipeptidyl-Peptidase IV Inhibitors",
			"Diphenhydramine",
			"Diphenidol",
			"Diphenoxylate",
			"Diphosphonates",
			"Dipivefrin",
			"Diprenorphine",
			"Dipropizine",
			"Dipyridamole",
			"Dipyrone",
			"Dirithromycin",
			"Disinfectants",
			"Disopyramide",
			"Disufenton sodium",
			"Disulfiram",
			"Ditiocarb",
			"Diuretics",
			"Dobutamine",
			"Docetaxel",
			"Docosanol",
			"Dofequidar",
			"Dofetilide",
			"Dolasetron mesylate",
			"Dolastatin 9",
			"Domperidone",
			"Donepezil",
			"Dong Quai",
			"Dopamine",
			"Dopamine Agents",
			"Dopamine Agonists",
			"Dopamine Antagonists",
			"Dopamine Uptake Inhibitors",
			"Dopexamine",
			"Dorzolamide",
			"Doxapram",
			"Doxazosin",
			"Doxepin",
			"Doxifluridine",
			"Doxofylline",
			"Doxorubicin",
			"Doxycycline",
			"Doxycycline hyclate",
			"Doxylamine",
			"Doxylamine succinate",
			"Droperidol",
			"Drospirenone",
			"Drospirenone and ethinyl estradiol combination",
			"Drotaverin",
			"Drotrecogin alfa activated",
			"Droxidopa",
			"Duloxetine",
			"Dutasteride",
			"Dydrogesterone",
			"Dynorphins",
			"Ebastine",
			"Ebselen",
			"Ecabet",
			"Echinacea",
			"Echinocandins",
			"Econazole",
			"Edetic Acid",
			"Edrophonium",
			"Efamol",
			"Efaproxiral",
			"Efavirenz",
			"Efavirenz, emtricitabine, tenofovir disoproxil fumarate drug combination",
			"Eflornithine",
			"Eicosapentaenoic acid ethyl ester",
			"Eletriptan",
			"Eleuthero",
			"Eliprodil",
			"Elsamicin A",
			"Eltoprazine",
			"Emetics",
			"Emivirine",
			"EMLA",
			"Emodin",
			"Emollients",
			"Emtricitabine",
			"Enalapril",
			"Enalaprilat",
			"Encainide",
			"Endocannabinoids",
			"Endocrine Disruptors",
			"Endorphins",
			"Endostatins",
			"Endothelial Growth Factors",
			"Endothelium-Dependent Relaxing Factors",
			"Enflurane",
			"Enfuvirtide",
			"English Lavender",
			"English Walnut",
			"Enkephalins",
			"Enoxacin",
			"Enoxaparin",
			"Enoximone",
			"Entacapone",
			"Entecavir",
			"Entonox",
			"Eosinophil Cationic Protein",
			"Eperisone",
			"Ephedra",
			"Ephedrine",
			"Epicatechin",
			"Epigallocatechin",
			"Epigallocatechin gallate",
			"Epinastine",
			"Epinephrine",
			"Epinephryl borate",
			"Epirubicin",
			"Eplerenone",
			"Epoetin Alfa",
			"Epoprostenol",
			"Epothilone B",
			"Epothilones",
			"Eprosartan",
			"Eptifibatide",
			"Equol",
			"Erdosteine",
			"Ergocalciferols",
			"Ergoloid Mesylates",
			"Ergonovine",
			"Ergotamine",
			"Erlotinib",
			"Ertapenem",
			"Erythritol",
			"Erythromycin",
			"Erythromycin Estolate",
			"Erythromycin Ethylsuccinate",
			"Erythromycin lactobionate",
			"Erythromycin stearate",
			"Esmolol",
			"Essential 9 forte",
			"Estazolam",
			"Estradiol",
			"Estradiol 9 beta-cypionate",
			"Estradiol 3-benzoate",
			"Estradiol valerate",
			"Estradiol Valerate, dienogest drug combination",
			"Estramustine",
			"Estrogen Antagonists",
			"Estrogen Receptor Modulators",
			"Estrogens",
			"Estrogens, Conjugated (USP)",
			"Estrogens, conjugated synthetic A",
			"Estrogens, conjugated synthetic B",
			"Estrogens, Esterified (USP)",
			"Estrone",
			"Estropipate",
			"Eszopiclone",
			"Etanidazole",
			"Etazolate",
			"Ethacrynic Acid",
			"Ethambutol",
			"Ethanol",
			"Ethanolamine oleate",
			"Ethinyl Estradiol",
			"Ethinyl estradiol, levonorgestrel drug combination",
			"Ethinyl Estradiol-Norgestrel Combination",
			"Ethiodized Oil",
			"Ethionamide",
			"Ethosuximide",
			"Ethyl 2-cyanoacrylate",
			"Ethyl Chloride",
			"Ethylene",
			"Ethynodiol Diacetate",
			"Ethynylestradiol mixture with norethindrone",
			"Etidronic Acid",
			"Etifoxine",
			"Etiracetam",
			"Etodolac",
			"Etomidate",
			"Etoposide",
			"Etoposide phosphate",
			"Etoricoxib",
			"Eucalyptus",
			"Eugenol",
			"European Mistletoe",
			"Eusol",
			"Evening Primrose",
			"Everolimus",
			"Exatecan",
			"Excitatory Amino Acid Agents",
			"Excitatory Amino Acid Agonists",
			"Excitatory Amino Acid Antagonists",
			"Excitatory Amino Acids",
			"Exemestane",
			"Exenatide",
			"Expectorants",
			"Ezetimibe",
			"Factor VIII",
			"Famciclovir",
			"Famotidine",
			"Farnesylthiosalicylic acid",
			"Fasudil",
			"Fe(III)-EDTA",
			"Febuxostat",
			"Felbamate",
			"Felodipine",
			"Femovan",
			"Fenfluramine",
			"Fennel",
			"Fenofibrate",
			"Fenofibric acid",
			"Fenoldopam",
			"Fenoterol",
			"Fenoterol, ipratropium drug combination",
			"Fenoverine",
			"Fenretinide",
			"Fentanyl",
			"Fenugreek",
			"Fenugreek seed meal",
			"Ferric Compounds",
			"Ferric gluconate",
			"Ferric oxide, saccharated",
			"Ferrous fumarate",
			"Ferrous gluconate",
			"Fertility Agents",
			"Fertility Agents, Female",
			"Ferulic acid",
			"Ferumoxytol",
			"Fexofenadine",
			"Fiacitabine",
			"Fialuridine",
			"Fibrin Fibrinogen Degradation Products",
			"Fibrin Foam",
			"Fibrin fragment D",
			"Fibrin Modulating Agents",
			"Fibrin Tissue Adhesive",
			"Fibrinolysin",
			"Fibrinolytic Agents",
			"Ficusin",
			"Finasteride",
			"Fingolimod",
			"Flavin Mononucleotide",
			"Flavopiridol",
			"Flavoxate",
			"Flax",
			"Flecainide",
			"Floxacillin",
			"Floxuridine",
			"Flt3 ligand protein",
			"Fluconazole",
			"Flucytosine",
			"Fludarabine",
			"Fludarabine monophosphate",
			"Fludrocortisone",
			"Fluindione",
			"Flumazenil",
			"Flunarizine",
			"Flunisolide",
			"Fluocinolone Acetonide",
			"Fluocinonide",
			"Fluorides",
			"Fluorides, Topical",
			"Fluorometholone",
			"Fluoromisonidazole",
			"Fluorophosphate",
			"Fluoroquinolones",
			"Fluorouracil",
			"Fluoxetine",
			"Fluoxymesterone",
			"Flupenthixol",
			"Flupenthixol decanoate",
			"Fluphenazine",
			"Fluphenazine depot",
			"Fluphenazine enanthate",
			"Flupirtine",
			"Fluprednisolone",
			"Flurandrenolone",
			"Flurbiprofen",
			"Flurbiprofen axetil",
			"Fluspirilene",
			"Flutamide",
			"Fluticasone",
			"Fluticasone, salmeterol drug combination",
			"Fluvastatin",
			"Fluvoxamine",
			"Folate",
			"Folic Acid",
			"Folic Acid Antagonists",
			"Folinic Acid",
			"Follicle Stimulating Hormone",
			"Fomepizole",
			"Fomivirsen",
			"Fondaparinux",
			"Formaldehyde",
			"Formononetin",
			"Formoterol",
			"Formyltetrahydrofolates",
			"Forskohlii",
			"Fosamprenavir",
			"Foscarnet",
			"Fosfestrol",
			"Fosfomycin",
			"Fosinopril",
			"Fosphenytoin",
			"Fospropofol disodium",
			"Fotemustine",
			"Frangula",
			"Free Radical Scavengers",
			"Freund's Adjuvant",
			"Frovatriptan",
			"Fucoidan",
			"Fulvestrant",
			"Furazolidone",
			"Furosemide",
			"Fusidic Acid",
			"GABA Agents",
			"GABA Agonists",
			"GABA Modulators",
			"GABA-A Receptor Agonists",
			"GABA-A Receptor Antagonists",
			"GABA-B Receptor Agonists",
			"Gabapentin",
			"Gadolinium 1,4,7,9-tetraazacyclododecane-N,N',N'',N'''-tetraacetate",
			"Galantamine",
			"Gallium nitrate",
			"Gallopamil",
			"Gamma-Aminobutyric Acid",
			"Gamma-Globulins",
			"Gamma-Tocopherol",
			"Ganciclovir",
			"Ganirelix",
			"Garcinia",
			"Garlic",
			"Gastric Inhibitory Polypeptide",
			"Gastrin-Releasing Peptide",
			"Gastrins",
			"Gastrodia",
			"Gastrointestinal Agents",
			"Gatifloxacin",
			"Gefarnate",
			"Gefitinib",
			"GEL protein, Gelonium multiflorum",
			"Gelatin Sponge, Absorbable",
			"Geldanamycin",
			"Gemcitabine",
			"Gemeprost",
			"Gemfibrozil",
			"Gemifloxacin",
			"Gemtuzumab",
			"Genistein",
			"Gentamicins",
			"Gentian",
			"Gentian Violet",
			"Gepirone",
			"Geranylgeranylacetone",
			"Gestodene",
			"Ginger",
			"Ginkgo",
			"Ginseng",
			"Glargine",
			"Gliclazide",
			"Glimepiride",
			"Glipizide",
			"Gliquidone",
			"Glucagon",
			"Glucagon-Like Peptide 1",
			"Glucocorticoids",
			"Glucosamine",
			"Glucuronyl glucosamine glycan sulfate",
			"Glutamic Acid",
			"Glutamine",
			"Glyburide",
			"Glycerol",
			"Glycine",
			"Glycocholic Acid",
			"Glycolic acid",
			"Glycopyrrolate",
			"Glycyrrhetinic Acid",
			"Glycyrrhizic Acid",
			"Gold Sodium Thiomalate",
			"Gold Sodium Thiosulfate",
			"Gonadotropins, Pituitary",
			"Goralatide",
			"Goserelin",
			"Gossypol",
			"Gossypol acetic acid",
			"Gotu Kola",
			"GR 99",
			"Gramicidin",
			"Granisetron",
			"Grape",
			"Grape Seed Extract",
			"Grapefruit Seed Extract",
			"Grepafloxacin",
			"Growth Hormone-Releasing Hormone",
			"GTPase-Activating Proteins",
			"Guaifenesin",
			"Guanfacine",
			"Guar",
			"Guarana",
			"Guava",
			"Gusperimus",
			"Gymnema Sylvestre",
			"Habekacin",
			"Hallucinogens",
			"Halobetasol",
			"Halofantrine",
			"Halofuginone",
			"Haloperidol",
			"Haloperidol decanoate",
			"Halothane",
			"Harringtonines",
			"Hawthorn",
			"HBOC 9",
			"Hemagglutinins",
			"Hematinics",
			"Hematologic Agents",
			"Hematoporphyrin Derivative",
			"Hematoporphyrins",
			"Hemostatics",
			"Heparin",
			"Heparin, Low-Molecular-Weight",
			"Hepatitis A Antibodies",
			"Hepatitis B Antibodies",
			"Hepatitis C Antibodies",
			"Hepcidin",
			"Heroin",
			"Hesperidin",
			"Hetastarch",
			"Hexachlorophene",
			"Hexetidine",
			"Hibiscus",
			"Higenamine",
			"Hirudins",
			"Histamine",
			"Histamine Antagonists",
			"Histamine H1 Antagonists",
			"Histamine H1 Antagonists, Non-Sedating",
			"Histamine H2 Antagonists",
			"Histamine H3 Antagonists",
			"Histamine phosphate",
			"Histidine",
			"Histone Deacetylase Inhibitors",
			"HIV Antibodies",
			"HIV Fusion Inhibitors",
			"HIV Integrase Inhibitors",
			"HIV Protease Inhibitors",
			"Homoharringtonine",
			"Homotaurine",
			"Honokiol",
			"Hoodia",
			"Hops",
			"Hormone Antagonists",
			"Hormones",
			"Hormones, Hormone Substitutes, and Hormone Antagonists",
			"Horny Goat Weed",
			"Horse Chestnut",
			"Horseradish",
			"Horseradish Tree",
			"HU 9",
			"Huperzine A",
			"Hyaluronic Acid",
			"Hydralazine",
			"Hydrochlorothiazide",
			"Hydrochlorothiazide, lisinopril drug combination",
			"Hydrocodone",
			"Hydrocortisone",
			"Hydrocortisone 9-butyrate 9-propionate",
			"Hydrocortisone acetate",
			"Hydrocortisone-9-butyrate",
			"Hydroflumethiazide",
			"Hydrogen Peroxide",
			"Hydromorphone",
			"Hydroquinidine",
			"Hydroquinone",
			"Hydrotalcite",
			"Hydroxocobalamin",
			"Hydroxychloroquine",
			"Hydroxycholecalciferols",
			"Hydroxycitric Acid",
			"Hydroxyflutamide",
			"Hydroxyitraconazole",
			"Hydroxymethylglutaryl-CoA Reductase Inhibitors",
			"Hydroxyurea",
			"Hydroxyzine",
			"Hypericin",
			"Hypnotics and Sedatives",
			"Hypoglycemic Agents",
			"Hypolipidemic Agents",
			"Ibandronic acid",
			"Ibotenic Acid",
			"Ibudilast",
			"Ibuprofen",
			"Ibutilide",
			"Icatibant",
			"Iclaprim",
			"Idarubicin",
			"Idazoxan",
			"Idebenone",
			"Idoxuridine",
			"Ifenprodil",
			"Ifetroban",
			"Ifosfamide",
			"Iloprost",
			"Imatinib",
			"Imidacloprid",
			"Imidapril",
			"Imipenem",
			"Imipramine",
			"Imiquimod",
			"Immune Sera",
			"Immunoconjugates",
			"Immunoglobulin A",
			"Immunoglobulin E",
			"Immunoglobulin Fab Fragments",
			"Immunoglobulin Fragments",
			"Immunoglobulin G",
			"Immunoglobulin Heavy Chains",
			"Immunoglobulin Idiotypes",
			"Immunoglobulin Light Chains",
			"Immunoglobulin M",
			"Immunoglobulins",
			"Immunoglobulins, Intravenous",
			"Immunologic Factors   9",
			"Immunosuppressive Agents   9",
			"Immunotoxins",
			"Incretins",
			"Indapamide",
			"Indapamide, perindopril drug combination",
			"Indian Frankincense",
			"Indinavir",
			"Indiplon",
			"Indirubin",
			"Indobufen",
			"Indole",
			"Indole-3-carbinol",
			"Indomethacin",
			"Infliximab",
			"Inosine Pranobex",
			"Inositol",
			"Insulin",
			"Insulin aspart",
			"Insulin glulisine",
			"Insulin LISPRO",
			"Insulin, Long-Acting",
			"Insulin, NPH",
			"Integrase Inhibitors",
			"Interferon Alfa-2a",
			"Interferon Alfa-2b",
			"Interferon alfacon-1",
			"Interferon beta 1a",
			"Interferon beta-1b",
			"Interferon Inducers",
			"Interferon omega 1",
			"Interferon Type I",
			"Interferon-alpha",
			"Interferon-beta",
			"Interferon-gamma",
			"Interferons",
			"Interleukin 1 Receptor Antagonist Protein",
			"Interleukin-9",
			"Interleukin-2",
			"Interleukin-4",
			"Inulin",
			"Iodine",
			"Iodine-9 anti-B1 antibody",
			"Ionomycin",
			"Ionophores",
			"Ipratropium",
			"Irbesartan",
			"Irinotecan",
			"Irofulven",
			"Iron",
			"Iron Chelating Agents",
			"Iron Supplement",
			"Iron-Dextran Complex",
			"ISIS 9",
			"ISIS 9",
			"Islet Amyloid Polypeptide",
			"Isoantibodies",
			"Isoflurane",
			"Isoflurophate",
			"Isoleucine",
			"Isoniazid",
			"Isoniazid, pyrazinamide, rifampin drug combination",
			"Isophosphamide mustard",
			"Isopropyl unoprostone",
			"Isoproterenol",
			"Isoquercitrin",
			"Isosorbide",
			"Isosorbide Dinitrate",
			"Isosorbide-5-mononitrate",
			"Isotretinoin",
			"Isotrifolin",
			"Isradipine",
			"Istradefylline",
			"Itraconazole",
			"Ivermectin",
			"JM 9",
			"Josamycin",
			"Juniper",
			"Kallikreins",
			"Kanamycin",
			"Kaolin",
			"Kava",
			"Keratolytic Agents",
			"Ketamine",
			"Ketanserin",
			"Ketoconazole",
			"Ketoprofen",
			"Ketorolac",
			"Ketorolac Tromethamine",
			"Ketotifen",
			"Keyhole-limpet hemocyanin",
			"Kinetin",
			"Kininogens",
			"Krestin",
			"KRM 9",
			"KRN 9",
			"Kudzu",
			"Labetalol",
			"Lacidipine",
			"Lactams",
			"Lactitol",
			"Lactulose",
			"Lafutidine",
			"Lamivudine",
			"Lamivudine, zidovudine drug combination",
			"Lamotrigine",
			"Landiolol",
			"Lanreotide",
			"Lansoprazole",
			"Lapatinib",
			"Latanoprost",
			"Lawsone",
			"Laxatives",
			"Lecithin",
			"Leflunomide",
			"Lenalidomide",
			"Lenograstim",
			"Lentinan",
			"Lepirudin",
			"Lercanidipine",
			"Letrozole",
			"Leucine",
			"Leucovorin",
			"Leukotriene Antagonists",
			"Leuprolide",
			"Levamisole",
			"Levan",
			"Levobunolol",
			"Levobupivacaine",
			"Levocabastine",
			"Levocetirizine",
			"Levodopa",
			"Levoleucovorin",
			"Levonorgestrel",
			"Levorphanol",
			"Levulinic acid",
			"LHRH, N-Ac-2-Nal(1)-4-Cl-Phe(2)-3-Pal(3)-Arg(5)-Glu(6)-AlaNH2(9)-",
			"LHRH, N-acetyl-(4-chlorophenylalanyl)(1)-(4-chlorophenylalanyl)(2)-tryptophyl...",
			"Liarozole",
			"Licorice",
			"Lidocaine",
			"Lincomycin",
			"Linezolid",
			"Lingonberry",
			"Linoleate",
			"Lipid Regulating Agents",
			"Lipoprotein-associated coagulation inhibitor",
			"Liposomal amphotericin B",
			"Lipoxin A4",
			"Lipoxygenase Inhibitors",
			"Lisinopril",
			"Lisofylline",
			"Listerine",
			"Lisuride",
			"Lithium",
			"Lithium Carbonate",
			"Lithospermate B",
			"Liver Extracts",
			"Lobeline",
			"Lobucavir",
			"Locust bean gum",
			"Lofexidine",
			"Lomefloxacin",
			"Lometrexol",
			"Lomustine",
			"Lonidamine",
			"Loperamide",
			"Lopinavir",
			"Loracarbef",
			"Loratadine",
			"Lorazepam",
			"Lormetazepam",
			"Lornoxicam",
			"Losartan",
			"Loteprednol etabonate",
			"Lovastatin",
			"Loxapine",
			"Loxoprofen",
			"Loxtidine",
			"Lucanthone",
			"Lugol's solution",
			"Lumefantrine",
			"Lumiracoxib",
			"Lupeol",
			"Lupus Coagulation Inhibitor",
			"Lurtotecan",
			"Lutein",
			"Luteolin",
			"Luteolytic Agents",
			"Lycium",
			"Lycopene",
			"Lymecycline",
			"Lynestrenol",
			"Lypressin",
			"Lysergic Acid Diethylamide",
			"Lysine",
			"Maca",
			"Mace",
			"Mafenide",
			"Mafosfamide",
			"Magnesium citrate",
			"Magnesium Hydroxide",
			"Magnesium Oxide",
			"Magnesium Salicylate",
			"Magnesium Sulfate",
			"Magnesium Supplement",
			"Magnesium trisilicate",
			"Maitake",
			"Malarone",
			"Malathion",
			"Maleic acid",
			"Malonate",
			"Maloprim",
			"Mandelic Acids",
			"Manganese",
			"Mango",
			"Mangosteen",
			"Manidipine",
			"Manna",
			"Mannitol",
			"Marimastat",
			"Marinobufagenin",
			"Marshmallow",
			"Maxacalcitol",
			"Maytansine",
			"Mazindol",
			"MDL 99",
			"Mebendazole",
			"Mebeverine",
			"Mecamylamine",
			"Mecarzole",
			"Mechlorethamine",
			"Meclizine",
			"Meclocycline",
			"Medroxyprogesterone",
			"Medroxyprogesterone Acetate",
			"Mefenamic Acid",
			"Mefloquine",
			"Megestrol",
			"Megestrol Acetate",
			"Meglumine antimoniate",
			"Melagatran",
			"Melanocyte-Stimulating Hormones",
			"Melarsoprol",
			"Melatonin",
			"Meloxicam",
			"Melphalan",
			"Memantine",
			"MEN 90",
			"Menadione",
			"Menaquinone",
			"Menatetrenone",
			"Menotropins",
			"Menthol",
			"Meperidine",
			"Mephenytoin",
			"Mepirodipine",
			"Mepivacaine",
			"Meropenem",
			"Mesalamine",
			"Mesna",
			"Mestranol",
			"Metadoxine",
			"Metaraminol",
			"Metformin",
			"Methacholine Chloride",
			"Methacycline",
			"Methadone",
			"Methadyl Acetate",
			"Methamphetamine",
			"Methanesulfonyl fluoride",
			"Methantheline",
			"Methazolamide",
			"Methenamine",
			"Methenamine hippurate",
			"Methicillin",
			"Methimazole",
			"Methionine",
			"Methocarbamol",
			"Methohexital",
			"Methotrexate",
			"Methotrimeprazine",
			"Methoxamine",
			"Methoxsalen",
			"Methoxyflurane",
			"Methyclothiazide",
			"Methyl 5-aminolevulinate",
			"Methyl salicylate",
			"Methylamphotericin B",
			"Methylcobalamin",
			"Methyldopa",
			"Methylene Blue",
			"Methylene diphosphonate",
			"Methylergonovine",
			"Methylnaltrexone",
			"Methylphenidate",
			"Methylprednisolone",
			"Methylprednisolone aceponate",
			"Methylprednisolone acetate",
			"Methylprednisolone Hemisuccinate",
			"Methyltestosterone",
			"Metoclopramide",
			"Metolazone",
			"Metoprolol",
			"Metoprolol succinate",
			"Metronidazole",
			"Metylperon",
			"Metyrapone",
			"Mexiletine",
			"Mezlocillin",
			"Mianserin",
			"Mibefradil",
			"Micafungin",
			"Miconazole",
			"Micronutrients",
			"Midazolam",
			"Midodrine",
			"Mifepristone",
			"Miglitol",
			"Miglustat",
			"Milbemycin",
			"Milk fat globule",
			"Milk Thistle",
			"Milnacipran",
			"Milrinone",
			"Miltefosine",
			"Mineral Oil",
			"Mineralocorticoids",
			"Minocycline",
			"Minoxidil",
			"Miotics",
			"Mirodenafil",
			"Mirtazapine",
			"Misonidazole",
			"Misoprostol",
			"Mitiglinide",
			"Mitochondrial uncoupling protein 2",
			"Mitochondrial uncoupling protein 3",
			"Mitogens",
			"Mitoguazone",
			"Mitolactol",
			"Mitomycins",
			"Mitotane",
			"Mitoxantrone",
			"Mivacurium",
			"Mizolastine",
			"Moclobemide",
			"Modafinil",
			"Moexipril",
			"Molgramostim",
			"Molindone",
			"Molsidomine",
			"Molybdenum",
			"Mometasone furoate",
			"Monensin",
			"Monoclonal antibody 9-1A",
			"Monolaurin",
			"Monophosphoryl lipid A",
			"Montelukast",
			"Moricizine",
			"Morphine",
			"Mosapride",
			"Motexafin gadolinium",
			"Motexafin lutetium",
			"Moxaverine",
			"Moxifloxacin",
			"Moxonidine",
			"MSM (Methylsulfonylmethane)",
			"Mugwort",
			"Mulungu",
			"Mung Bean",
			"Mupirocin",
			"Muramidase",
			"MuramylNAc-Ala-isoGln-Lys-tripeptide-PE",
			"Muromonab-CD3",
			"Muscarinic Agonists",
			"Muscarinic Antagonists",
			"Muscimol",
			"Muscle Relaxants, Central",
			"Mustard Gas",
			"Mycophenolate mofetil",
			"Mycophenolic Acid",
			"Mydriatics",
			"Myeloablative Agonists",
			"Myeloma Proteins",
			"Myrrh",
			"N 9",
			"N(1),N(9)-diethylnorspermine",
			"N(1),N(9)-bis(ethyl)homospermine",
			"N,N-diethyl-2-((4-phenylmethyl)phenoxy)ethanamine",
			"N,N-dimethylarginine",
			"N,N-Dimethyltryptamine",
			"N-(2-aminoethyl)-5-isoquinolinesulfonamide",
			"N-(2-aminophenyl)-4-((4-pyridin-3-ylpyrimidin-2-ylamino)methyl)benzamide",
			"N-acetyl-1-aspartylglutamic acid",
			"N-Methyl-3,4-methylenedioxyamphetamine",
			"N-Methylaspartate",
			"N-monoacetylcystine",
			"Nabilone",
			"Nabumetone",
			"Nadolol",
			"Nadroparin",
			"Nafamostat",
			"Nafarelin",
			"Nafcillin",
			"Naftifine",
			"Naftopidil",
			"Nalbuphine",
			"Nalidixic Acid",
			"Nalmefene",
			"Naloxone",
			"Naltrexone",
			"Nandrolone",
			"Nandrolone decanoate",
			"Nandrolone phenpropionate",
			"Naphazoline",
			"Naphthoquinone",
			"Naproxen",
			"Naproxen-n-butyl nitrate",
			"Naratriptan",
			"Narcotic Antagonists",
			"Narcotics",
			"Naringenin",
			"Nasal Decongestants",
			"Natamycin",
			"Nateglinide",
			"Natriuretic Agents",
			"Natriuretic Peptide, Brain",
			"Natriuretic Peptide, C-Type",
			"Naxagolide",
			"Nebivolol",
			"Nedaplatin",
			"Nedocromil",
			"Neem",
			"Nefazodone",
			"Nefiracetam",
			"Nefopam",
			"Nelfinavir",
			"Neomycin",
			"Neosaxitoxin",
			"Neostigmine",
			"Netilmicin",
			"Neurokinin A",
			"Neuromuscular Agents",
			"Neuromuscular Blocking Agents",
			"Neuromuscular Depolarizing Agents",
			"Neuromuscular Nondepolarizing Agents",
			"Neuroprotective Agents",
			"Neuroserpin",
			"Neurotransmitter Agents   9",
			"Neurotransmitter Uptake Inhibitors",
			"Neurotropin",
			"Nevirapine",
			"NG-Nitroarginine Methyl Ester",
			"Niacin",
			"Niacinamide",
			"Nicardipine",
			"Nicergoline",
			"Nickel",
			"Niclosamide",
			"Nicorandil",
			"Nicotinamide",
			"Nicotine",
			"Nicotine polacrilex",
			"Nicotinic Acids",
			"Nicotinic Agonists",
			"Nifedipine",
			"Nifurtimox",
			"Nigella",
			"Nikkomycin",
			"Nilutamide",
			"Nilvadipine",
			"Nimesulide",
			"Nimodipine",
			"Nimorazole",
			"Nisoldipine",
			"Nitazoxanide",
			"Nitisinone",
			"Nitrazepam",
			"Nitrendipine",
			"Nitric Oxide",
			"Nitric Oxide Donors",
			"Nitroarginine",
			"Nitroaspirin",
			"Nitrofurantoin",
			"Nitrofurazone",
			"Nitrogen Mustard Compounds",
			"Nitroglycerin",
			"Nitroprusside",
			"Nitrous Oxide",
			"Nizatidine",
			"Nociceptin",
			"Nolatrexed",
			"Noni",
			"Nonivamide",
			"Nonoxynol",
			"Nonsteroidal Anti-Androgens",
			"Nootropic Agents",
			"Noracycline",
			"Nordihydroguaiaretic Acid",
			"Norelgestromin",
			"Norepinephrine",
			"Norethandrolone",
			"Norethindrone",
			"Norethindrone acetate",
			"Norethindrone enanthate",
			"Norfloxacin",
			"Norflurane",
			"Norgestimate",
			"Norgestimate, ethinyl estradiol drug combination",
			"Norgestrel",
			"Norinyl",
			"Nortriptyline",
			"Noscapine",
			"Novobiocin",
			"NSC 99",
			"Nucleic Acid Synthesis Inhibitors",
			"Nutmeg",
			"Nystatin",
			"O(6)-benzylguanine",
			"O-(chloroacetylcarbamoyl)fumagillol",
			"O-desmethylvenlafaxine",
			"Ochratoxin A",
			"Octenidine",
			"Octreotide",
			"Octylmethoxycinnamate",
			"Octylonium",
			"Ofloxacin",
			"Olaflur",
			"Olanzapine",
			"Oleander",
			"Oleanol",
			"Oleoyl-estrone",
			"Olive",
			"Olmesartan",
			"Olmesartan medoxomil",
			"Olopatadine",
			"Olsalazine",
			"Oltipraz",
			"Omalizumab",
			"Omega 3 Fatty Acid",
			"Omega-Conotoxins",
			"Omega-N-Methylarginine",
			"Omeprazole",
			"Omeprazole, sodium bicarbonate drug combination",
			"Onapristone",
			"Ondansetron",
			"ONO 9",
			"ONYX9",
			"Opioid Peptides",
			"Opium",
			"Opium Poppy",
			"Oprelvekin",
			"Orange",
			"Oregano",
			"Orexins",
			"Orlistat",
			"Ornithine",
			"Orphenadrine",
			"Ortho Evra",
			"Oseltamivir",
			"Oviol",
			"Oxacillin",
			"Oxaliplatin",
			"Oxandrolone",
			"Oxatomide",
			"Oxazepam",
			"Oxazolidinones",
			"Oxcarbazepine",
			"Oxethazaine",
			"Oxfendazole",
			"Oxiconazole",
			"Oxitropium",
			"Oxybenzone",
			"Oxybutynin",
			"Oxycodone",
			"Oxymetazoline",
			"Oxymorphone",
			"Oxypurinol",
			"Oxytetracycline",
			"Oxytocin",
			"Ozagrel",
			"Paclitaxel",
			"Palivizumab",
			"Palmidrol",
			"Palmitic Acid",
			"Palonosetron",
			"Pamidronate",
			"Pancreatic Polypeptide",
			"Pancreatin",
			"Pancrelipase",
			"Pantoprazole",
			"Pantothenic Acid",
			"Papain",
			"Papaverine",
			"Papaya",
			"Paraldehyde",
			"Parasympatholytics",
			"Parecoxib",
			"Paromomycin",
			"Paroxetine",
			"Parsley",
			"Parthenolide",
			"Passionflower",
			"Pectin",
			"Pegaspargase",
			"Peginterferon alfa-2a",
			"Peginterferon alfa-2b",
			"Pemetrexed",
			"Pemoline",
			"Penciclovir",
			"Penclomedine",
			"Penicillamine",
			"Penicillanic Acid",
			"Penicillin G",
			"Penicillin G Benzathine",
			"Penicillin G Procaine",
			"Penicillin V",
			"PENTA",
			"Pentamidine",
			"Pentazocine",
			"Pentetic Acid",
			"Pentobarbital",
			"Pentosan Sulfuric Polyester",
			"Pentostatin",
			"Pentoxifylline",
			"Peoniflorin",
			"Peppermint",
			"Peppermint oil",
			"Pepsin A",
			"Performance-Enhancing Substances",
			"Pergolide",
			"Perhexiline",
			"Perilla alcohol",
			"Perillyl Alcohol",
			"Perindopril",
			"Peripheral Nervous System Agents   9",
			"Permethrin",
			"Permixon",
			"Perphenazine",
			"Petrolatum",
			"Phenelzine",
			"Phenethyl isothiocyanate",
			"Phenethylisothiocyanate",
			"Phenindione",
			"Pheniramine",
			"Phenobarbital",
			"Phenol",
			"Phenoxybenzamine",
			"Phenprocoumon",
			"Phentermine",
			"Phentolamine",
			"Phenylacetic acid",
			"Phenylalanine",
			"Phenylephrine",
			"Phenylethyl Alcohol",
			"Phenylmethylpyrazolone",
			"Phenylpropanolamine",
			"Phenytoin",
			"Phosphocreatine",
			"Phosphodiesterase 3 Inhibitors",
			"Phosphodiesterase 4 Inhibitors",
			"Phosphodiesterase 5 Inhibitors",
			"Phosphodiesterase Inhibitors",
			"Phosphonoacetic Acid",
			"Phosphoramide Mustards",
			"Phosphoramidic acid",
			"Phosphorus Supplement",
			"Photosensitizing Agents",
			"Phthalocyanine",
			"Phylloquinone",
			"Physostigmine",
			"Phytoestrogens",
			"Phytosterol",
			"Picibanil",
			"Picolinic acid",
			"Picosulfate sodium",
			"Pigment epithelium-derived factor",
			"Pilocarpine",
			"Pilsicainide",
			"Pimagedine",
			"Pimecrolimus",
			"Pimonidazole",
			"Pimozide",
			"Pinaverium",
			"Pindolol",
			"Pioglitazone",
			"Pipamperone",
			"Pipecuronium",
			"Piperacillin",
			"Piperacillin-tazobactam combination product",
			"Piperaquine",
			"Piperazine",
			"Piperazine citrate",
			"Piracetam",
			"Pirarubicin",
			"Pirenzepine",
			"Pirfenidone",
			"Piribedil",
			"Pirinitramide",
			"Piritrexim",
			"Piroxicam",
			"Pitavastatin",
			"Pituitary Adenylate Cyclase-Activating Polypeptide",
			"Pixantrone",
			"PK 95",
			"Plantain",
			"Plasma Substitutes",
			"Plasminogen",
			"Plasminogen Activator Inhibitor 1",
			"Plasminogen Inactivators",
			"Platelet Aggregation Inhibitors",
			"Platelet Factor 4",
			"Platelet-derived growth factor BB",
			"Pleconaril",
			"Plicamycin",
			"Podophyllotoxin",
			"Poke",
			"Policosanol",
			"Polidocanol",
			"Poly I-C",
			"Poly ICLC",
			"Poly(maleic acid-styrene)neocarzinostatin",
			"Polyene phosphatidylcholine",
			"Polyestradiol phosphate",
			"Polygeline",
			"Polyhexamethylene biguanide",
			"Polymethyl Methacrylate",
			"Polymyxin B",
			"Polymyxins",
			"Polyvinyl alcohol formaldehyde foam",
			"Pomegranate",
			"Poractant alfa",
			"Porfiromycin",
			"Posaconazole",
			"Potassium Channel Blockers",
			"Potassium Citrate",
			"Potassium iodate",
			"Potassium phosphate",
			"Potassium Supplement",
			"Povidone",
			"Povidone-Iodine",
			"Pralidoxime",
			"Pramipexol",
			"Pramlintide",
			"Pramoxine",
			"Pranlukast",
			"Prasugrel",
			"Pravastatin",
			"Praziquantel",
			"Prazosin",
			"Prednicarbate",
			"Prednimustine",
			"Prednisolone",
			"Prednisolone acetate",
			"Prednisolone hemisuccinate",
			"Prednisolone phosphate",
			"Prednisone",
			"Pregabalin",
			"Pregnanolone",
			"Prilocaine",
			"Primaquine",
			"Primidone",
			"Pristinamycin",
			"Proanthocyanidin",
			"Probenecid",
			"Probucol",
			"Procainamide",
			"Procaine",
			"Procarbazine",
			"Procaterol",
			"Prochlorperazine",
			"Procyanidin",
			"Proflavine",
			"Progesterone",
			"Progestins",
			"Proguanil",
			"Proline",
			"Promethazine",
			"Propacetamol",
			"Propafenone",
			"Propantheline",
			"Propiverine",
			"Propofol",
			"Propolis",
			"Propoxycaine",
			"Propranolol",
			"Propyl Gallate",
			"Propylthiouracil",
			"Prostaglandin Antagonists",
			"Protamines",
			"Protease Inhibitors",
			"Protective Agents",
			"Protein C",
			"Protein C Inhibitor",
			"Protein Kinase Inhibitors",
			"Protein S",
			"Protein Synthesis Inhibitors",
			"Proteinase Inhibitory Proteins, Secretory",
			"Prothionamide",
			"Proton Pump Inhibitors",
			"Protriptyline",
			"Proxymetacaine",
			"Pseudoephedrine",
			"Psilocybine",
			"Psoralens",
			"Psychotropic Drugs",
			"Psyllium",
			"Puerarin",
			"Pulmonary Surfactant-Associated Protein B",
			"Pulmonary Surfactant-Associated Protein C",
			"Pulmonary Surfactant-Associated Protein D",
			"Pulmonary Surfactant-Associated Proteins",
			"Pulmonary Surfactants",
			"Purinergic Agents",
			"Purinergic Antagonists",
			"Purinergic P1 Receptor Agonists",
			"Purinergic P1 Receptor Antagonists",
			"Purinergic P2 Receptor Antagonists",
			"Purinergic P2Y Receptor Antagonists",
			"Purple Butterbur",
			"Pycnogenols",
			"Pyranoprofen",
			"Pyrantel",
			"Pyrantel Pamoate",
			"Pyrazinamide",
			"Pyrazole",
			"Pyridostigmine Bromide",
			"Pyridoxal",
			"Pyridoxal isonicotinoyl hydrazone",
			"Pyridoxal Phosphate",
			"Pyridoxamine",
			"Pyridoxine",
			"Pyrimethamine",
			"Pyronaridine",
			"Pyruvate",
			"QS 9",
			"Quercetin",
			"Quetiapine",
			"Quinacrine",
			"Quinagolide",
			"Quinapril",
			"Quinidine",
			"Quinidine gluconate",
			"Quinine",
			"Quinuclidin-3'-yl-1-phenyl-1,2,3,4-tetrahydroisoquinoline-2-carboxylate monos...",
			"Quinupristin-dalfopristin",
			"Rabeprazole",
			"Raclopride",
			"Radiation-Protective Agents",
			"Radiation-Sensitizing Agents",
			"Radish",
			"Raloxifene",
			"Raltitrexed",
			"Ramatroban",
			"Ramipril",
			"Ramosetron",
			"Ranitidine",
			"Ranitidine bismuth citrate",
			"Ranolazine",
			"Ranpirnase",
			"Rasagiline",
			"Rasburicase",
			"Raspberry",
			"Rauwolfia",
			"Razoxane",
			"Reaferon",
			"Rebamipide",
			"Reboxetine",
			"Receptors, Antigen, B-Cell",
			"Red Cinchona",
			"Red Clover",
			"Red Yeast",
			"Red yeast rice",
			"Regadenoson",
			"Reishi",
			"Remifentanil",
			"Renal Agents",
			"Renzapride",
			"Repaglinide",
			"Reproductive Control Agents",
			"Reproterol",
			"Reserpine",
			"Respiratory System Agents",
			"Resveratrol",
			"Reteplase",
			"Retinamide",
			"Retinol",
			"Retinol acetate",
			"Retinol palmitate",
			"Reverse Transcriptase Inhibitors",
			"Rho(D) Immune Globulin",
			"Ribavirin",
			"Riboflavin",
			"Rice bran oil",
			"Rifabutin",
			"Rifampin",
			"Rifamycin SV",
			"Rifamycins",
			"Rifapentine",
			"Rifaximin",
			"Rilmenidine",
			"Riluzole",
			"Rimantadine",
			"Rimexolone",
			"Risedronic acid",
			"Risperidone",
			"Ritanserin",
			"Ritodrine",
			"Ritonavir",
			"Rituximab",
			"Rivastigmine",
			"Rizatriptan",
			"Rocuronium",
			"Rofecoxib",
			"Rolipram",
			"Romidepsin",
			"Ropinirole",
			"Ropivacaine",
			"Roscovitine",
			"Rose Hips",
			"Rosemary",
			"Rosiglitazone",
			"Rosmarinic acid",
			"Rosuvastatin",
			"Roxithromycin",
			"Ruboxistaurin",
			"Rue",
			"Rutin",
			"S 98",
			"S-methylthiocitrulline",
			"SA 9",
			"Safingol",
			"Sage",
			"Salacia",
			"Salicylates",
			"Salicylic Acid",
			"Salicylsalicylic acid",
			"Salivary plasminogen activator alpha 1, Desmodus rotundus",
			"Salmeterol",
			"Salmon calcitonin",
			"Samarium ethylenediaminetetramethylenephosphonate",
			"Saporin",
			"Saquinavir",
			"Sarpogrelate",
			"Saruplase",
			"Satraplatin",
			"Saw Palmetto",
			"Saxagliptin",
			"Sch 96",
			"Sch 94",
			"Schisandra",
			"Sclerosing Solutions",
			"Scopolamine",
			"Sea Buckthorn",
			"Secnidazole",
			"Secoisolariciresinol",
			"Secretin",
			"Secretory Leukocyte Peptidase Inhibitor",
			"Selective Estrogen Receptor Modulators",
			"Selegiline",
			"Selenium",
			"Selenium Supplement",
			"Selenomethylselenocysteine",
			"Semustine",
			"Senna",
			"Senna Extract",
			"Sennoside A&B",
			"Sensory System Agents",
			"Seocalcitol",
			"Serine",
			"Serine Proteinase Inhibitors",
			"Serotonin",
			"Serotonin 5-HT2 Receptor Antagonists",
			"Serotonin 5-HT3 Receptor Antagonists",
			"Serotonin 5-HT4 Receptor Agonists",
			"Serotonin 5-HT4 Receptor Antagonists",
			"Serotonin Agents",
			"Serotonin Antagonists",
			"Serotonin Receptor Agonists",
			"Serotonin Uptake Inhibitors",
			"Sertaconazole",
			"Sertindole",
			"Sertraline",
			"Sevelamer",
			"Sevoflurane",
			"Shark Cartilage",
			"Shiga Toxins",
			"Sibutramine",
			"Sildenafil",
			"Silicon",
			"Silicon phthalocyanine",
			"Silver Nitrate",
			"Silver Sulfadiazine",
			"Silybin",
			"Silymarin",
			"Simendan",
			"Simethicone",
			"Simvastatin",
			"Sirolimus",
			"Sisomicin",
			"Sitagliptin",
			"Sitosterol",
			"Sizofiran",
			"Soblidotin",
			"Sodium arsenite",
			"Sodium Benzoate",
			"Sodium Channel Blockers",
			"Sodium Chloride Symporter Inhibitors",
			"Sodium Fluoride",
			"Sodium fluoride topical preparation",
			"Sodium Hypochlorite",
			"Sodium Morrhuate",
			"Sodium Oxybate",
			"Sodium phosphate",
			"Sodium Potassium Chloride Symporter Inhibitors",
			"Sodium Salicylate",
			"Sodium selenate",
			"Sodium sulfate",
			"Sodium Tetradecyl Sulfate",
			"Sodium thiosulfate",
			"Somatostatin",
			"Sorafenib",
			"Sorbitol",
			"Sorivudine",
			"Sotalol",
			"Soy Bean",
			"Sparfloxacin",
			"Specific substance maruyama",
			"Spectinomycin",
			"Spermatocidal Agents",
			"Spiradoline",
			"Spiramycin",
			"Spirapril",
			"Spironolactone",
			"Spirulina",
			"Squalamine",
			"Squaric acid dibutyl ester",
			"SR 99B",
			"SR 91A",
			"ST 9",
			"St. John's Wort",
			"Staurosporine",
			"Stavudine",
			"Stevia",
			"Stevioside",
			"Stinging Nettle",
			"Stiripentol",
			"Strawberry",
			"Streptokinase",
			"Streptomycin",
			"Streptozocin",
			"Strontium ranelate",
			"SU 9",
			"Substance P",
			"Succimer",
			"Succinylcholine",
			"Sucralfate",
			"Sucrose polyester",
			"Sufentanil",
			"Sugarcane",
			"Sulbactam",
			"Sulfacetamide",
			"Sulfadiazine",
			"Sulfadoxine",
			"Sulfadoxine-pyrimethamine",
			"Sulfalene",
			"Sulfamethazine",
			"Sulfamethizole",
			"Sulfamethoxazole",
			"Sulfanilamides",
			"Sulfasalazine",
			"Sulfisoxazole",
			"Sulforafan",
			"Sulforaphane",
			"Sulindac",
			"Sulindac sulfone",
			"Sulperazone",
			"Sulpiride",
			"Sulprostone",
			"Sultamicillin",
			"Sulthiame",
			"Sultopride",
			"Sumatriptan",
			"Sunflower",
			"Sunitinib",
			"Sunscreening Agents",
			"Superoxide Dismutase",
			"Suramin",
			"Symbicort",
			"Sympatholytics",
			"Synephrine",
			"Syntometrine",
			"Tacrine",
			"Tacrolimus",
			"Tadalafil",
			"Tafenoquine",
			"Tagatose",
			"Talaporfin",
			"Talinolol",
			"Tamoxifen",
			"Tamsulosin",
			"Tandospirone",
			"Tangerine",
			"Tannic Acid",
			"Tanshinone",
			"Taurine",
			"Taurochenodeoxycholic Acid",
			"Taurolidine",
			"Tauroursodeoxycholic acid",
			"Taxane",
			"Tazarotene",
			"Tazobactam",
			"Tea",
			"Tea Tree",
			"Tea Tree Oil",
			"Technetium Tc 9m Pentetate",
			"Tedisamil",
			"Teferrol",
			"Tegafur",
			"Tegaserod",
			"Teicoplanin",
			"Telenzepine",
			"Telithromycin",
			"Telmisartan",
			"Telmisartan, hydrochlorothiazide drug combination",
			"Temazepam",
			"Temocillin",
			"Temoporfin",
			"Temozolomide",
			"TEMPO",
			"Tempol",
			"Tenecteplase",
			"Teniposide",
			"Tenofovir",
			"Tenofovir disoproxil",
			"Tenoxicam",
			"Terazosin",
			"Terbinafine",
			"Terbutaline",
			"Terconazole",
			"Terephthalylidene dicamphor sulfonic acid",
			"Terfenadine",
			"Teriparatide",
			"Terlipressin",
			"Testolactone",
			"Testosterone",
			"Testosterone 9 beta-cypionate",
			"Testosterone enanthate",
			"Testosterone undecanoate",
			"Tetrabenazine",
			"Tetracaine",
			"Tetracycline",
			"Tetraethylammonium",
			"Tetrahydrocannabinol",
			"Tetrahydrofolates",
			"Tetrahydropalmatine",
			"Tetrahydrouridine",
			"Tetrahydrozoline",
			"Tetrathiomolybdate",
			"Tetrodotoxin",
			"Tezosentan",
			"Thalidomide",
			"Theobromine",
			"Theophylline",
			"Thiamine",
			"Thiamphenicol",
			"Thiazole-4-carboxamide adenine dinucleotide",
			"Thienamycins",
			"Thioacetazone",
			"Thiocitrulline",
			"Thioctic Acid",
			"Thioguanine",
			"Thiopental",
			"Thioridazine",
			"Thiorphan",
			"Thiotepa",
			"Thiothixene",
			"Threonine",
			"Thrombin",
			"Thromboplastin",
			"Thymalfasin",
			"Thyme",
			"Thymic humoral factor gamma 2",
			"Thymogen",
			"Thymol",
			"Thymopentin",
			"Thyrotropin-Releasing Hormone",
			"Tiagabine",
			"Tianeptine",
			"Tiapride",
			"Tiaprofenic acid",
			"Tibolone",
			"Ticagrelor",
			"Ticarcillin",
			"Ticarcillin-clavulanic acid",
			"Ticlopidine",
			"Tigecycline",
			"Tiludronic acid",
			"Timolol",
			"Tin",
			"Tin etiopurpurin",
			"Tin Fluorides",
			"Tin mesoporphyrin",
			"Tinidazole",
			"Tinoridine",
			"Tinzaparin",
			"Tiotropium",
			"Tipifarnib",
			"Tipranavir",
			"Tirapazamine",
			"Tirilazad",
			"Tirofiban",
			"Tiropramide",
			"Tissue Plasminogen Activator",
			"Titanium dioxide",
			"Tizanidine",
			"TNFR-Fc fusion protein",
			"Tobramycin",
			"Tocolytic Agents",
			"Tocopherols",
			"Tocopherylquinone",
			"Tocotrienol, alpha",
			"Tocotrienols",
			"Tofisopam",
			"Tolazamide",
			"Tolbutamide",
			"Tolcapone",
			"Tolfenamic acid",
			"Tolnaftate",
			"Tolonium Chloride",
			"Tolperisone",
			"Tolterodine",
			"Tomato",
			"Topiramate",
			"Topoisomerase I Inhibitors",
			"Topoisomerase Inhibitors",
			"Topotecan",
			"Torcetrapib",
			"Toremifene",
			"Torsemide",
			"Trabectedin",
			"Trabedersen",
			"Trace Elements",
			"Tramadol",
			"Tramazoline",
			"Trandolapril",
			"Tranexamic Acid",
			"Tranilast",
			"Tranquilizing Agents",
			"Tranylcypromine",
			"Trapidil",
			"Trastuzumab",
			"Travoprost",
			"Trazodone",
			"Treosulfan",
			"Treprostinil",
			"Trestolone",
			"Tretinoin",
			"Triacetin",
			"Triamcinolone",
			"Triamcinolone Acetonide",
			"Triamcinolone diacetate",
			"Triamcinolone hexacetonide",
			"Triamterene",
			"Triazolam",
			"Tribulus",
			"Trichlormethiazide",
			"Trichloroethylene",
			"Trichosanthin",
			"Trichostatin A",
			"Triclabendazole",
			"Triclocarban",
			"Triclosan",
			"Trientine",
			"Trifluoperazine",
			"Trifluridine",
			"Triflusal",
			"Trihexyphenidyl",
			"Trilostane",
			"Trimebutine",
			"Trimetazidine",
			"Trimethaphan",
			"Trimethaphan camsylate",
			"Trimethobenzamide",
			"Trimethoprim",
			"Trimethoprim-Sulfamethoxazole Combination",
			"Trimetrexate",
			"Trioxsalen",
			"Tripterygium",
			"Triptolide",
			"Triptorelin",
			"Trisequens",
			"Troclosene",
			"Trofosfamide",
			"Troglitazone",
			"Tropicamide",
			"Tropisetron",
			"Trospium chloride",
			"Trovafloxacin",
			"Troxacitabine",
			"Troxerutin",
			"Trypsin Inhibitors",
			"Tryptophan",
			"Tubulin Modulators",
			"Tulobuterol",
			"Tumor Necrosis Factor Ligand Superfamily Member 9",
			"Turmeric",
			"Turmeric extract",
			"Tyramine",
			"Tyrosine",
			"Tyrothricin",
			"Ubiquinone",
			"Udenafil",
			"Unithiol",
			"Urapidil",
			"Urethane",
			"Uric Acid",
			"Uricosuric Agents",
			"Urinastatin",
			"Ursodeoxycholic Acid",
			"Valacyclovir",
			"Valdecoxib",
			"Valerian",
			"Valganciclovir",
			"Valine",
			"Valproic Acid",
			"Valrubicin",
			"Valsartan",
			"Vanadium",
			"Vanadyl sulfate",
			"Vancomycin",
			"Vanoxerine",
			"Vapreotide",
			"Vardenafil",
			"Varenicline",
			"Vasoactive Intestinal Peptide",
			"Vasoconstrictor Agents",
			"Vasodilator Agents",
			"Vasopressins",
			"Vatalanib",
			"Vecuronium Bromide",
			"Venlafaxine",
			"Verapamil",
			"Verteporfin",
			"Vesnarinone",
			"Vidarabine",
			"Vidarabine Phosphate",
			"Vigabatrin",
			"Vildagliptin",
			"Vinblastine",
			"Vinca Alkaloids",
			"Vincristine",
			"Vindesine",
			"Vinorelbine",
			"Vinpocetine",
			"Viscum album peptide",
			"Vitamin A",
			"Vitamin B 9",
			"Vitamin B 6",
			"Vitamin B Complex",
			"Vitamin B1",
			"Vitamin B9",
			"Vitamin B2",
			"Vitamin B3",
			"Vitamin B5",
			"Vitamin B6",
			"Vitamin B7",
			"Vitamin B9",
			"Vitamin C",
			"Vitamin D",
			"Vitamin D2",
			"Vitamin D3",
			"Vitamin E",
			"Vitamin K",
			"Vitamin K 1",
			"Vitamin K 2",
			"Vitamin K 3",
			"Vitamin MK 7",
			"Vitamins",
			"Vitremer",
			"Voglibose",
			"Voriconazole",
			"Vorinostat",
			"Warfarin",
			"Whey Protein",
			"White Willow",
			"Wobenzym",
			"Wormwood",
			"Xenon",
			"Ximelagatran",
			"Xylometazoline",
			"Yellow Dock",
			"Yohimbe",
			"Yohimbine",
			"Zafirlukast",
			"Zalcitabine",
			"Zaleplon",
			"Zanamivir",
			"ZD 9",
			"Ziconotide",
			"Zidovudine",
			"Zileuton",
			"Zinc",
			"Zinc Oxide",
			"Zinc Sulfate",
			"Zinc Supplement",
			"Zinostatin",
			"Ziprasidone",
			"Zoledronic acid",
			"Zolmitriptan",
			"Zolpidem",
			"Zonisamide",
			"Zopiclone",
			"Zotepine",
			"(1-6)-alpha-glucomannan",
			"(3-aminopropyl)(n-butyl)phosphinic acid",
			"1 alpha,9-dihydroxyvitamin D3",
			"1 alpha-hydroxyergocalciferol",
			"1,3-dipropyl-8-(3-noradamantyl)xanthine",
			"1,4,7,9-tetraazacyclododecane- 1,4,7,9-tetraacetic acid",
			"1,4-dihydropyridine",
			"1-(carboxymethylthio)tetradecane",
			"1-hydroxycholecalciferol",
			"9-deazaaminopterin",
			"9-hydroxycamptothecin",
			"9-hydroxyprogesterone",
			"9-alpha-hydroxy-progesterone caproate",
			"9-N,N-diethylcarbamoyl-4-methyl-4-azaandrostane-3-one",
			"2',3'-dideoxy-5-fluoro-3'-thiacytidine",
			"2'-deoxy-2'-(fluoromethylene)cytidine",
			"2'-fluoro-5-methylarabinosyluracil",
			"2,3-dihydro-1H-imidazo(1,2-b)pyrazole",
			"2,4-thiazolidinedione",
			"2,5-Dimethoxy-4-Methylamphetamine",
			"2,6-diaminopurine",
			"2-((((2-chloroethyl)nitrosoamino)carbonyl)amino)propanamide",
			"2-(4-(quinolin-2-yl-methoxy)phenyl)-2-cyclopentylacetic acid",
			"2-Aminopurine",
			"2-chloro-3'-deoxyadenosine",
			"2-methoxyestradiol",
			"2-tert-butylhydroquinone",
			"3'-azido-3'-deoxythymidine 5'-triphosphate",
			"3,3'-diindolylmethane",
			"3,4-diaminopyridine",
			"3,4-dihydroxyphenylethanol",
			"3,4-Methylenedioxyamphetamine",
			"3-(2,2,2-trimethylhydrazine)propionate",
			"3-(2,4-dimethoxybenzylidene)anabaseine",
			"3-iodo-2-hydroxy-6-methoxy-N-((1-ethyl-2-pyrrolidinyl)methyl)benzamide",
			"3-Iodobenzylguanidine",
			"3-keto-desogestrel",
			"3-n-butylphthalide",
			"4'-deoxydoxorubicin",
			"4'-N-benzoylstaurosporine",
			"4,5,6,7-tetrahydroisoxazolo(5,4-c)pyridin-3-ol",
			"4-Aminopyridine",
			"4-des-dimethylaminotetracycline",
			"4-Hydroxycoumarins",
			"4-hydroxytamoxifen",
			"4-phenylbutyric acid",
			"4-tert-butyl-4'-methoxydibenzoylmethane",
			"5,6-dimethylxanthenoneacetic acid",
			"5-(1-aziridinyl)-2,4-dinitrobenzamide",
			"5-alpha Reductase Inhibitors",
			"5-chloro-2-methyl-4-isothiazolin-3-one",
			"5-ethynyluracil",
			"5-Hydroxytryptophan",
			"5-methoxypsoralen",
			"6-Aminocaproic Acid",
			"6-Mercaptopurine",
			"6-O-palmitoylascorbic acid",
			"7,7'-dimethoxy-(4,4'-bi-1,3-benzodioxole)-5,5'-dicarboxylic acid dimethyl ester",
			"7-hydroxystaurosporine",
			"8-chloro-cyclic adenosine monophosphate",
			"8-epi-prostaglandin F2alpha", "9-amino-9-camptothecin",
			"9-hydroxy-risperidone", "9-nitrocamptothecin" };
}
